### ISSUE TITLE
Which part of the version to bump

### ISSUE THREAD

**Issue by toby-coleman** [FragileTech/bump-version#1]
How should I control which part of the version is bumped when using this action, i.e. major/minor/patch?

Would be good to add an example to the README showing how.

**Comment by florisla** [comment]
This is controlled in the configuration file bumpversion.cfg.  See https://pypi.org/project/bump2version/

**Comment by jmrodriguez-lab** [comment]
From what I've read it is not. You need to specify whether this change is a mayor / minor / patch, etc...
This is usually done by adding some hashtag in the commit text (namely `#patch`, `#major`, `#minor` or by using conventional commits, etc).

**Comment by chanhosuh** [comment]
You would have to do something like the following:
```
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: version.md
        commit_name: Your Company Bot
        commit_email: bot@your-company.com
        login: your-bot-login
        token: "${{ secrets.BOT_TOKEN }}"
        part: "${{ env.part }}"
```

Notice the last line.  `part` is in fact an input to the action code; by default the code assumes it is "patch".  You can use a previous step to parse it out of the commit message as the previous poster suggests and then store it as an env arg.
